headers = []
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Volumes/imac/开发项目/IBC-AI-TRADE-OS/06-repos/portal/.next"
publishOrigin = "config"
commandOrigin = "config"
base = "/Volumes/imac/开发项目/IBC-AI-TRADE-OS/06-repos/portal"
command = "prisma generate && next build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]